# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Landing Hero
  description: Landing Hero Section
  icon: "cottage"
  tags: ["hero"]

# Defines the structure of this component, as well as the default values
blueprint:
  headline: Reclaim your health
  description: Life without Type 2 diabetes is possible. Now you can safely reduce or eliminate Type 2 diabetes medications and shed unwanted weight with the Twin Health program.Twin Health is a new pilot program* offered by Blue Care Network.
  videoSrc: https://player.vimeo.com/video/851460585?loop=false&amp;autoplay=false&amp;muted=false&amp;gesture=media&amp;playsinline=true&amp;byline=false&amp;portrait=false&amp;title=false&amp;speed=true&amp;transparent=false&amp;customControls=true
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
